disabled_rules: # rule identifiers to exclude from running
  # - closing_brace
  # - colon
  # - comma
  # - conditional_binding_cascade
  # - control_statement
  # - custom_rules
  # - cyclomatic_complexity
  # - empty_count
  # - file_length
  - force_cast
  # - force_try
  # - force_unwrapping
  # - function_body_length
  # - function_parameter_count
  # - leading_whitespace
  # - legacy_constant
  # - legacy_constructor
  # - line_length
  # - missing_docs
  # - nesting
  # - opening_brace
  # - operator_whitespace
  # - return_arrow_whitespace
  # - statement_position
  # - todo
  # - trailing_newline
  # - trailing_semicolon
  # - trailing_whitespace
  # - type_body_length
  - type_name
  - valid_docs
  # - variable_name
opt_in_rules: # some rules are only opt-in
  - empty_count
  # - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
# paths to ignore during linting.
excluded:
  - Carthage
  - Pods
  - fastlane
# configurable rules can be customized from this configuration file
force_try: warning
force_unwrapping: warning
line_length: 220 # warning
type_body_length: 300 # warning
file_length: 700
function_body_length: 60
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: 50 # only warning
  excluded: iPhone # excluded via string
variable_name:
  min_length:
    warning: 2
    error: 1
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - URLRequest
    - URLString
